export default {
	CREATE_PALETTE: 'CREATE_PALETTE',
	UPDATE_PALETTE: 'UPDATE_PALETTE',
	DELETE_PALETTE: 'DELETE_PALETTE',
	TOGGLE_DELETE_MODAL: 'TOGGLE_DELETE_MODAL',
	SET_DELETING_PALETTE: 'SET_DELETING_PALETTE',
	RESET_DELETING_PALETTE: 'RESET_DELETING_PALETTE'
}