export default {
	SET_EDITING_PALETTE: 'SET_EDITING_PALETTE',
	ADD_COLOR_TO_PALETTE: 'ADD_COLOR_TO_PALETTE',
	REMOVE_COLOR_FROM_PALETTE: 'REMOVE_COLOR_FROM_PALETTE',
	CLEAR_PALETTE: 'CLEAR_PALETTE',
	TOGGLE_SAVE_MODAL: 'TOGGLE_SAVE_MODAL',
	RESET_EDITING_PALETTE: 'RESET_EDITING_PALETTE'
}